cacheFolder: ./build/.cache/yarn/cache

enableImmutableInstalls: false

enableInlineBuilds: false

enableTelemetry: false

#httpProxy: 'http://localhost:1095'

httpTimeout: 60000

#httpsProxy: 'http://localhost:1095'

installStatePath: ./build/.cache/yarn/install-state.gz

logFilters:
  - code: YN0006
    level: discard
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'
