name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install .[dev]

    - name: Build the extension
      run: |
        jlpm 
        jlpm build:prod
        hatch build

    - name: Upload extension packages
      uses: actions/upload-artifact@v4
      with:
        name: extension-artifacts
        path: dist/*
        if-no-files-found: error

    - name: Build JupyterLite site
      run: |
        jupyter lite build --output-dir _output

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_output
