name: Improve Issue Titles
on:
  issues:
    types: [opened]
jobs:
  improve-titles:
    runs-on: ubuntu-latest
    steps:
      - name: Improve Issue Titles
        uses: horw/issue-title-ai@v0.1.6b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          auto-update: true
          model: gemini-2.0-flash
          quiet: true